/**
 * Menu that takes a selected course and updates its message with the name selected
 * so that it can be fetched by its caller.
 * # Command
 * * This menu is generated by the {@link commands/addcourse | Add course command}, with jointclass=true
 * @packageDocumentation
 */
import { Events, BaseInteraction } from 'discord.js';

module.exports = {
  name: Events.InteractionCreate,
  async execute(interaction: BaseInteraction) {
    if (!interaction.isStringSelectMenu()) return;
    if (!(interaction.customId === 'joint-course')) return;
    interaction.editReply({ content: interaction.values[0] + ' selected!', components: [] });
  },
};