/**
 * Handles a stringSelectMenu with CustomId 'role-remove',
 * removing an entered role from the list of roles, and deleting its associated server role
 * # Command
 * * This menu is generated by the {@link commands/removeoptrole | Remove opt role command}
 * @packageDocumentation
 */
import { Events, BaseInteraction } from 'discord.js';
import { getListFromFile, saveListToFile } from '../../helpers/functions';
import { OptionalRole } from '../../helpers/role';

module.exports = {
  name: Events.InteractionCreate,
  async execute(interaction: BaseInteraction) {
    if (!interaction.isStringSelectMenu()) return;
    if (!(interaction.customId === 'role-remove')) return;
    if (!(interaction.guild && interaction.member)) return;
    await interaction.deferUpdate();
    const rolesList = getListFromFile('data/optRoles.json') as OptionalRole[];
    const rolesSelected = interaction.values;
    const removedRoles: string[] = [];
    // Assign roles
    for (const selectedElement of rolesSelected) {
      for (const course of rolesList) {
        if (course.name != selectedElement) continue;
        const optRole = await interaction.guild.roles.fetch(course.role.id);
        // Deletes role fully
        if (optRole) interaction.guild.roles.delete(optRole, 'Deleted as part of Optional Role deletion');
        rolesList.splice(rolesList.indexOf(course), 1);
        removedRoles.push(course.name);
        saveListToFile(rolesList, 'data/optroles.json');
      }
    }
    await interaction.editReply({ content: 'Roles removed: ' + removedRoles.join(', '), components: [] });
  },
};